services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/var/www/html
    working_dir: /var/www/html
    container_name: crud-admin
    networks:
      - crud-network
    user: "${UID:-1000}:${GID:-1000}"

  webserver:
    image: nginx:alpine
    volumes:
      - .:/var/www/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8080:80"
    container_name: crud-nginx 
    networks:
      - crud-network

  db:
    image: postgres:latest
    container_name: crud-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${DB_DATABASE:-crud_db}
      POSTGRES_USER: ${DB_USERNAME:-crud}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-1224}
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "${DB_PORT:-5432}:5432"
    networks:
      - crud-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USERNAME:-crud}"]
      timeout: 5s
      retries: 10

  pgadmin:
    image: dpage/pgadmin4
    container_name: crud-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL:-admin@admin.com}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD:-admin}
    ports:
      - "${PGADMIN_PORT:-8081}:80"
    networks:
      - crud-network


  init-permissions:
    image: alpine
    volumes:
      - .:/var/www/html
    command: sh -c "chmod -R 775 /var/www/html/storage /var/www/html/bootstrap/cache && chown -R www-data:www-data /var/www/html"
    depends_on:
      - app

networks:
  crud-network:

volumes:
  db_data:
  mongo_data: